name = "yngmin-me-frontend"
compatibility_date = "2024-04-14"

[build]
pages_build_output_dir = "out"
upload_format = "directory"
command = "npm run build"

pages_build_output_dir = ".vercel/output/static"
